### ISSUE TITLE
Liens cassés

### ISSUE THREAD

**Issue by arobase-che** [informaticienzero/informaticienzero.github.io#2]
Coucou,

Deux lien vers OC sont cassés [ici](https://github.com/informaticienzero/informaticienzero.github.io/blob/master/_posts/2016-12-29-ma%C3%AEtriser-les-pointeurs-et-les-tableaux-en-c.markdown).

Je propose de remplacer ces liens par ceux-ci :
 - https://zestedesavoir.com/tutoriels/2787/la-verite-sur-les-tableaux-et-pointeurs-en-c/
 - http://sdz.tdct.org/sdz/ableaux-pointeurs-et-allocation-dynamique.html

Merci :)

**Comment by informaticienzero** [comment]
Corrigé, merci. :)
